# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
title: Zeddic
email: scott@zeddic.com
# description: >- # this means to ignore newlines until "baseurl:"
#  The personal website of Scott Bailey
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zeddic.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: zeddic

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
# permalink: /:categories/:year/:month/:day/:title
